language: node_js
node_js: node
services:
- mongodb
addons:
  apt:
    sources:
    - mongodb-3.2-precise
    packages:
    - mongodb-org-server
deploy:
  provider: heroku
  api_key:
    secure: a93FsjlYwnFIi3Y9H02wX0BI2bYbyIWpnMJuz8267fAMoFRrKnT3QHgfqlA1Cm2fjVQ+Ap+mPFNu189o66SvLzirgtLqMJddpszZMh0eE/fqXLBS59Oz4Eiu4cpYqZe1T+M3XvrGCUJhEYzS3TdVMmjqFXNRb3hiZFcw9hZ4G9T8I79TE6VDJGqpY7gHit3Ji7B7JIsaG5s4TQlZLvM4sTSSLdS+SQjlMQKuPKh+9XABPl5ViFzWzoYrY4y5eVlcKkRiEXY7GEWB7IucoMMivxZKHq804jOdfTzqPwvQcJIaALeyRhjCK939BY+UFMX+so2q4HtDcrQ4zj0auyxT9AoU/pnSUHZLCNB3MZQuqIQ8dP4TxzwoXWSk7Cp48jzxPEDPJJ9VMRhOfIr7qyREMnVdg3C/mpAFAjLpVtCRsAgySzNgMVAtV2w6pafpAEayz6gbGnYCD3gJ1gTuxwYED4WBjDwG98nyRLceSaK49UYTRGrgwGhGAQXwDCq1vM25czzIA3CeF/PqI/mYm6FEkXPjh0G4Wy+ZwUE4l6TreobDDy5HnUDtKfsJQqKKIBLl78OngjDpbMIEY6JaZnfe6uYWCZ7BabSN1AdxnIvbWt4PJSZ0kqPTRwS3gVyni3iubKGfb8DdJxYVSbZzdcnvYTqd59oyWshxwA2Tv5n1trQ=
  app: mongo-shopping-list
  on:
    repo: Holmberg18/mongo-shopping-list
